version: "3"
services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: 'todos'
    volumes:
      - ~/docker-volumes/coroutine-todos/postgresql:/var/lib/postgresql/data