spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/todos?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  sql:
    init:
      mode: always
